import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { getSettings } from "../lib/api";

export default function Home({ settings }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Headless WordPress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href={settings.url}>Your Title</a>
        </h1>

        <p className={styles.description}>
          What's your App about?{" "}
          <code className={styles.code}>Your Tagline</code>
        </p>

        <p className={styles.description}>
          Now we'll query your Posts!!{" "}
          <code className={styles.code}>Ready?</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Your posts will come here &rarr;</h2>
            <p>We'll create a query with WPGraphQL and render it here</p>
          </a>

          {/* Here's a hint on the Map Loop  */}
          {/* {xxx.map(({ xxx }) => (
            <a key={xxx.id} className={styles.card}>
              <h2>{xxx.title} &rarr;</h2>
              <p>{xxx.content}</p>
            </a>
          ))} */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const settings = await getSettings();

  return {
    props: { settings },
  };
}
